WITH C AS (
SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE (CAR_ID NOT IN
    (SELECT DISTINCT(CAR_ID)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'))
    AND (CAR_TYPE IN ('세단', 'SUV'))
)
SELECT CAR_ID AS CAR_ID, CAR_TYPE AS CAR_TYPE, FLOOR((30 * DAILY_FEE * (1 - (discount_rate/100)))) AS `FEE`
FROM C INNER JOIN
    (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE SUBSTRING(duration_type, 1, 2) = '30') AS P
    USING(CAR_TYPE)
WHERE ((30 * DAILY_FEE * (1 - (discount_rate/100))) >= 500000)
    AND ((30 * DAILY_FEE * (1 - (discount_rate/100))) < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;