SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    MAX(p.PRICE) * SUM(o.AMOUNT) AS TOTAL_SALES
FROM (
    SELECT
        PRODUCT_ID, 
        AMOUNT,
        PRODUCE_DATE
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5) AS o
LEFT JOIN (
    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        PRICE
    FROM FOOD_PRODUCT) AS p USING(PRODUCT_ID)
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, o.PRODUCT_ID