SELECT *
FROM (SELECT
        ANIMAL_ID,
        ANIMAL_TYPE,
        NAME
      FROM ANIMAL_INS
      WHERE SEX_UPON_INTAKE LIKE 'Intact%') AS i 
    INNER JOIN (SELECT ANIMAL_ID FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%') AS o USING (ANIMAL_ID)
ORDER BY ANIMAL_ID