WITH INFO AS (
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE (MCDP_CD = 'CS') AND (DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13') AND (APNT_CNCL_YN = 'N')
)
SELECT I.APNT_NO, P.PT_NAME, P.PT_NO, I.MCDP_CD, D.DR_NAME, I.APNT_YMD
FROM INFO AS I
    INNER JOIN PATIENT AS P USING(PT_NO)
    INNER JOIN DOCTOR AS D ON I.MDDR_ID = D.DR_ID
ORDER BY I.APNT_YMD;