WITH most_review_user AS (
    SELECT
        MEMBER_ID,
        COUNT(MEMBER_ID) AS MEMBERS
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY MEMBERS DESC
    LIMIT 1
)
SELECT
    p.MEMBER_NAME,
    r.REVIEW_TEXT,
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT
        MEMBER_ID,
        MEMBER_NAME
    FROM MEMBER_PROFILE
    WHERE MEMBER_ID = (SELECT MEMBER_ID FROM most_review_user)) AS p
INNER JOIN REST_REVIEW AS r USING(MEMBER_ID)
ORDER BY REVIEW_DATE, r.REVIEW_TEXT