SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F INNER JOIN 
    (SELECT CATEGORY, MAX(PRICE) AS `MAX_PRICE`
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) AS M USING(CATEGORY)
WHERE F.PRICE = M.MAX_PRICE
ORDER BY M.MAX_PRICE DESC;