WITH base AS (
    SELECT
        CATEGORY,
        PRICE,
        MAX(PRICE) OVER (PARTITION BY CATEGORY) AS MAX_PRICE,
        PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM base
WHERE PRICE = MAX_PRICE
ORDER BY MAX_PRICE DESC