WITH DIST_ID AS (
    SELECT ID
    FROM ECOLI_DATA 
), CHILD_ID AS (
    SELECT
        PARENT_ID,
        COUNT(PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
)
SELECT
    d.ID,
    COALESCE(c.CHILD_COUNT, 0) AS CHILD_COUNT
FROM DIST_ID AS d LEFT JOIN CHILD_ID AS c ON d.ID = c.PARENT_ID
ORDER BY d.ID