SELECT
    YEAR(s.SALES_DATE) AS YEAR,
    MONTH(s.SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM (
    SELECT
        USER_ID,
        GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL) AS u
    INNER JOIN ONLINE_SALE AS s USING(USER_ID)
GROUP BY YEAR(s.SALES_DATE), MONTH(s.SALES_DATE), GENDER
ORDER BY YEAR, MONTH, GENDER