WITH TYPE_DISCOUNT_PLAN AS (
    SELECT
        CAR_TYPE,
        IF(LENGTH(DURATION_TYPE) = 11, LEFT(DURATION_TYPE, 1), LEFT(DURATION_TYPE, 2)) AS DURATION_TYPE,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
), NOT_USE_CAR AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
), CAN_USE_CAR AS (
    SELECT
        H.HISTORY_ID,
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE
    FROM (SELECT CAR_ID, CAR_TYPE, DAILY_FEE FROM CAR_RENTAL_COMPANY_CAR) AS C
        INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H USING(CAR_ID)
    WHERE C.CAR_ID NOT IN (SELECT * FROM NOT_USE_CAR) AND (C.CAR_TYPE IN ('세단', 'SUV'))
), base AS (
    SELECT
        DISTINCT
            CAR_ID,
            CAR_TYPE,
            DAILY_FEE,
            DISCOUNT_RATE
    FROM CAN_USE_CAR AS C
        INNER JOIN (SELECT CAR_TYPE, DISCOUNT_RATE FROM TYPE_DISCOUNT_PLAN WHERE DURATION_TYPE = 30) AS D USING(CAR_TYPE)
)
SELECT
    CAR_ID,
    CAR_TYPE,
    ROUND(30 * DAILY_FEE * (1- (DISCOUNT_RATE / 100))) AS FEE
FROM base
WHERE ROUND(30 * (DAILY_FEE * (1- (DISCOUNT_RATE / 100)))) >= 500000
    AND ROUND(30 * (DAILY_FEE * (1- (DISCOUNT_RATE / 100)))) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;