WITH FST AS( -- 차종류만 체크한 아우터조인된 테이블
SELECT C.CAR_ID, R.START_DATE, R.END_DATE
  FROM CAR_RENTAL_COMPANY_CAR C
  LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R
    ON C.CAR_ID = R.CAR_ID
 WHERE 1=1 
   AND C.CAR_TYPE IN ('세단','SUV')
)
, DIS AS (
         SELECT CAR_TYPE, DISCOUNT_RATE 
           FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
          WHERE CAR_TYPE IN ('세단','SUV')
            AND DURATION_TYPE = '30일 이상'
)
SELECT C1.CAR_ID , C1.CAR_TYPE, ROUND((C1.DAILY_FEE * (1-D1.DISCOUNT_RATE/100) *30), 0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C1
  JOIN DIS D1
    ON C1.CAR_TYPE = D1.CAR_TYPE
 WHERE 1=1 
  AND C1.CAR_TYPE IN ('세단','SUV')
  AND C1.CAR_ID NOT IN (
                        SELECT F.CAR_ID
                          FROM FST F
                         WHERE 1=1
                          AND F.START_DATE <= '2022-11-30'
                          AND F.END_DATE   >= '2022-11-01'
                        )
 AND ROUND((C1.DAILY_FEE * (1-D1.DISCOUNT_RATE/100) *30), 0) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C1.CAR_TYPE ASC, C1.CAR_ID DESC