WITH I AS
(SELECT ID, 
    (CASE
        WHEN (SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'Python'))
            AND (EXISTS 
                    (SELECT 1 FROM SKILLCODES S
                     WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE))) THEN 'A'
        WHEN SKILL_CODE & (SELECT `CODE` FROM SKILLCODES WHERE NAME = 'C#')  THEN 'B'
        WHEN EXISTS 
                (SELECT 1 FROM SKILLCODES S
                 WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE)) THEN 'C'
    END) AS GRADE
FROM DEVELOPERS AS D)
SELECT I.GRADE, D.ID, D.EMAIL
FROM DEVELOPERS AS D INNER JOIN I USING(ID)
WHERE I.GRADE IS NOT NULL
ORDER BY I.GRADE, D.ID;