WITH RECURSIVE HOURS AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)
SELECT
    HOUR,
    COALESCE(`COUNT`, 0) AS `COUNT`
FROM HOURS AS h
LEFT JOIN (
    SELECT
        HOUR(DATETIME) AS HOUR,
        COUNT(*) AS `COUNT`
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) AS a USING(HOUR)
ORDER BY HOUR