WITH RECURSIVE cte AS (
    SELECT 0 AS n
    UNION ALL
    SELECT n + 1 FROM cte WHERE n < 23
)

SELECT H.n AS `HOUR`, COALESCE(C.COUNT, 0) AS `COUNT`
FROM
    (SELECT n FROM cte) AS H LEFT OUTER JOIN 
    (SELECT HOUR(DATETIME) AS `HOUR`, COUNT(*) AS `COUNT`
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)) AS C ON H.n = C.HOUR;