SELECT C.CAR_ID, COALESCE(A.AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM 
    (SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID) AS C LEFT JOIN
    (SELECT CAR_ID, '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (START_DATE <= '2022-10-16') AND (END_DATE >= '2022-10-16')) AS A USING(CAR_ID)
ORDER BY C.CAR_ID DESC;