SELECT P.PRODUCT_CODE, (P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P INNER JOIN
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) AS O USING(PRODUCT_ID)
ORDER BY SALES DESC, P.PRODUCT_CODE;