SELECT
    CAR_ID, 
    COALESCE(AVAILABILITY, '대여 가능') AS AVAILABILITY
FROM (
    SELECT
        DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS c
LEFT JOIN (
    SELECT
        DISTINCT CAR_ID,
        '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (DATE(START_DATE) <= '2022-10-16' AND DATE(END_DATE) >= '2022-10-16')) AS r USING (CAR_ID)
ORDER BY CAR_ID DESC