WITH BOOK_INFO AS (
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, (B.PRICE * S.SALES) AS TOTAL_SALES
    FROM BOOK AS B INNER JOIN
        (SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
        GROUP BY BOOK_ID) AS S USING(BOOK_ID)
    )
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, I.CATEGORY, SUM(I.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK_INFO AS I INNER JOIN AUTHOR AS A USING(AUTHOR_ID)
GROUP BY A.AUTHOR_ID, I.CATEGORY
ORDER BY A.AUTHOR_ID, I.CATEGORY DESC;