SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
WHERE EXISTS
        (SELECT 'clear'
         FROM SKILLCODES AS S
         WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE))
ORDER BY ID;