# SELECT
#     i.REST_ID,
#     i.REST_NAME,
#     i.FOOD_TYPE,
#     i.FAVORITES,
#     i.ADDRESS,
#     COALESCE(r.SCORE, 0) AS SCORE
# FROM REST_INFO AS i LEFT JOIN
#     (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
#      FROM REST_REVIEW
#      GROUP BY REST_ID) AS r USING(REST_ID)
# WHERE i.ADDRESS LIKE '%서울%'
# ORDER BY SCORE DESC, i.FAVORITES DESC

SELECT
    I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
    ROUND(R.REVIEW_SCORE, 2) AS SCORE
FROM REST_INFO AS I INNER JOIN
    (SELECT REST_ID, AVG(REVIEW_SCORE) AS `REVIEW_SCORE`
     FROM REST_REVIEW GROUP BY REST_ID) AS R USING(REST_ID)
WHERE I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;