SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R INNER JOIN
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX
    FROM REST_INFO
    GROUP BY FOOD_TYPE) AS M USING(FOOD_TYPE)
WHERE R.FAVORITES = M.MAX
ORDER BY R.FOOD_TYPE DESC;