SELECT MONTH(C.START_DATE) AS MONTH, C.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C INNER JOIN
    (SELECT CAR_ID, COUNT(*) AS COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE (YEAR(START_DATE) = 2022) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) AS S USING (CAR_ID)
WHERE (S.COUNT >= 5) AND (YEAR(START_DATE) = 2022) AND (MONTH(START_DATE) BETWEEN 8 AND 10)
GROUP BY C.CAR_ID, MONTH(C.START_DATE)
ORDER BY MONTH, C.CAR_ID DESC;