SELECT
    CONCAT('/home/grep/src/', f.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM (
    SELECT
        *
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)) AS b
INNER JOIN USED_GOODS_FILE AS f USING(BOARD_ID)
ORDER BY f.FILE_ID DESC