SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I LEFT OUTER JOIN
    (SELECT DISTINCT(PARENT_ITEM_ID) AS 'CHECK' FROM ITEM_TREE) AS T ON I.ITEM_ID = T.CHECK
WHERE T.CHECK IS NULL
ORDER BY I.ITEM_ID DESC;