WITH UPON_INTAKE AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
), UPON_OUTCOME AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_OUTCOME
    FROM ANIMAL_OUTS
    WHERE (SEX_UPON_OUTCOME LIKE 'Neutered%') OR (SEX_UPON_OUTCOME LIKE 'Spayed%')
)
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM UPON_INTAKE AS I INNER JOIN UPON_OUTCOME AS O USING(ANIMAL_ID)
ORDER BY I.ANIMAL_ID;