WITH INFO AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H USING(CAR_ID)
    WHERE CAR_TYPE = '트럭'
), DISCOUNT AS (
    SELECT 
        (CASE
            WHEN DURATION_TYPE = '7일 이상' THEN 7
            WHEN DURATION_TYPE = '30일 이상' THEN 30
            ELSE 90
        END) AS DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)
SELECT 
    HISTORY_ID,
    (CASE
        WHEN DURATION >= 90
            THEN FLOOR(DURATION * DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE = 90) / 100))
        WHEN DURATION >= 30
            THEN FLOOR(DURATION * DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE = 30) / 100))
        WHEN DURATION >= 7
            THEN FLOOR(DURATION * DAILY_FEE * (1 - (SELECT DISCOUNT_RATE FROM DISCOUNT WHERE DURATION_TYPE = 7) / 100))
        ELSE DURATION * DAILY_FEE
    END) AS `FEE`
FROM INFO
ORDER BY FEE DESC, HISTORY_ID DESC;