WITH TRUCK AS (
    SELECT
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE = '트럭'
), TRUCK_DISCOUNT_PLAN AS (
    SELECT
        CAR_TYPE,
        IF(LENGTH(DURATION_TYPE) = 11, LEFT(DURATION_TYPE, 1), LEFT(DURATION_TYPE, 2)) AS DURATION_TYPE,
        DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
    WHERE CAR_TYPE = '트럭'
), base AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        CAR_TYPE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
        INNER JOIN TRUCK AS T USING(CAR_ID)
), base_duration_type AS (
    SELECT
        HISTORY_ID,
        CAR_ID,
        CAR_TYPE,
        DAILY_FEE,
        DURATION,
        CASE
            WHEN DURATION < 7 THEN 0
            WHEN DURATION < 30 THEN 7
            WHEN DURATION < 90 THEN 30
            ELSE 90
        END AS DURATION_TYPE
    FROM base
)
SELECT
    HISTORY_ID,
    IF(b.DURATION_TYPE = 0, DAILY_FEE * b.DURATION, FLOOR((DAILY_FEE * (1- (d.DISCOUNT_RATE / 100))) * b.DURATION))AS FEE
FROM base_duration_type AS b LEFT JOIN TRUCK_DISCOUNT_PLAN AS d USING(DURATION_TYPE)
ORDER BY FEE DESC, HISTORY_ID DESC