SELECT D.DEPT_ID, D.DEPT_NAME_EN, E.AVG AS AVG_SAL
FROM HR_DEPARTMENT AS D INNER JOIN
    (SELECT DEPT_ID, ROUND(AVG(SAL)) AS `AVG`
     FROM HR_EMPLOYEES
     GROUP BY DEPT_ID) AS E USING(DEPT_ID)
ORDER BY AVG_SAL DESC;