WITH FIRST_ECOLI AS (
    SELECT DISTINCT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), SECOND_ECOLI AS (
    SELECT DISTINCT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT * FROM FIRST_ECOLI)
)
SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT * FROM SECOND_ECOLI)
ORDER BY ID