SELECT B.CATEGORY, SUM(S.SUM) AS TOTAL_SALES
FROM BOOK AS B INNER JOIN
    (SELECT BOOK_ID, SUM(SALES) AS `SUM`
    FROM BOOK_SALES
    WHERE (YEAR(SALES_DATE) = 2022) AND (MONTH(SALES_DATE) = 1)
    GROUP BY BOOK_ID) AS S USING(BOOK_ID)
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;