WITH `ORDER` AS (
    SELECT *
    FROM FIRST_HALF
    UNION
    SELECT *
    FROM JULY
)
SELECT FLAVOR
FROM 
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
     FROM `ORDER`
     GROUP BY FLAVOR
     ORDER BY TOTAL_ORDER DESC) AS O
LIMIT 3;