SELECT U.USER_ID, U.NICKNAME, D.SUM AS TOTAL_SALES
FROM USED_GOODS_USER AS U INNER JOIN 
    (SELECT WRITER_ID, SUM(PRICE) AS `SUM`
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID) AS D ON U.USER_ID = D.WRITER_ID
WHERE D.SUM >= 700000
ORDER BY TOTAL_SALES;